# Pytorch

In [1]:
import torch

## Tensors

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
type(t1)


torch.Tensor

In [4]:
t1.shape

torch.Size([])

In [5]:
t2=torch.tensor([1.,3,4,5])
t2

tensor([1., 3., 4., 5.])

In [6]:
t2.shape

torch.Size([4])

In [7]:
t3=torch.tensor([[3,4,5],
                 [6,7,8]])
t3

tensor([[3, 4, 5],
        [6, 7, 8]])

In [8]:
t3.shape

torch.Size([2, 3])

In [9]:
t3=torch.tensor([[[3,4,5],
                 [6,7,8]],
                 [[3,6,7],
                 [7,8,9]]])
t3

tensor([[[3, 4, 5],
         [6, 7, 8]],

        [[3, 6, 7],
         [7, 8, 9]]])

In [10]:
t3.shape

torch.Size([2, 2, 3])

## Gradient
### Gradient descent is an optimization algorithm which is commonly-used to train machine learning models and neural networks.

In [11]:
x=torch.tensor(4.)
w=torch.tensor(6.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [12]:
y=x*w+b
y

tensor(29., grad_fn=<AddBackward0>)

## Compute Derivatives


In [13]:
y.backward()

In [14]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(4.)
dy/db: tensor(1.)


In [15]:
import numpy as np

In [16]:
x=np.array([[1.,2,3],
            [4,5,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
y=torch.from_numpy(x)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [18]:
type(x),type(y)

(numpy.ndarray, torch.Tensor)

In [19]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [20]:
# tensor to numpy
z=y.numpy()
z

array([[1., 2., 3.],
       [4., 5., 6.]])